# Generated by Django 2.0 on 2018-02-21 13:04

from django.db import migrations, models
import django.db.models.deletion

import gbackup.fields
import gbackup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', gbackup.fields.PathField(help_text='Absolute path on the local filesystem', max_length=4096, unique=True)),
                ('new', models.BooleanField(db_index=True, default=True, help_text='Indicates this is a new entry and needs scanning. It forces an update to the metadata next scan.')),
                ('st_mode', models.IntegerField(null=True)),
                ('st_mtime_ns', models.IntegerField(null=True)),
                ('st_size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('objid', models.BinaryField(primary_key=True, serialize=False)),
                ('payload', models.BinaryField(blank=True, null=True)),
                ('children', models.ManyToManyField(related_name='parents', to='gbackup.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', gbackup.fields.PathField(help_text='Root directory of this snapshot', max_length=4096)),
                ('date', models.DateTimeField(db_index=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gbackup.Object')),
            ],
        ),
        migrations.AddField(
            model_name='fsentry',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbackup.Object'),
        ),
        migrations.AddField(
            model_name='fsentry',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent FSEntry. This relation defines the hierarchy of the filesystem. It is null for the root entry of the backup set.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='gbackup.FSEntry'),
        ),
    ]
