# Generated by Django 2.0 on 2017-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='gbackup.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='payload',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
