repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.263'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --show-source]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.393
    hooks:
      - id: pyright
        additional_dependencies:
          - types-requests
          - pydantic
          - click
          - rich
          - msgpack
          - PyNaCl
          - b2sdk
          - lz4
          - yappi
          - toml
          - fastapi
          - uvicorn
          - typer

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.19.0
    hooks:
      - id: eslint
        files: ^backathon-web
        args: [--fix --max-warnings 1]
        additional_dependencies:
          - "eslint@9.19.0"
          - "@vue/eslint-config-prettier@10.1.0"
          - "@vue/eslint-config-typescript@14.3.0"
          - "eslint-plugin-vue@9.32.0"
          - "jiti@2.4.2"
          - "typescript@5.7.3"
        types: [file]
        types_or: [javascript, ts, vue]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        files: ^backathon-web
        types_or: [css, javascript, vue, ts, json]
        additional_dependencies:
          - prettier@3.0.0
          - prettier-plugin-organize-imports@3.2.3