repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.263'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --show-source]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-pytz
          - django-stubs[compatible-mypy]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [css, javascript, vue, ts, json]
        additional_dependencies:
          - prettier@3.0.0
          - prettier-plugin-organize-imports@3.2.3