[build-system]
requires = ["mcon"]
build-backend = "mcon.pybuild"

[project]
name = "backathon"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = [
    "msgpack",
    "PyNaCl",
    "colorlog",
    "rich",
    "b2sdk",
    "pydantic",
    "click~=8.1.0",
]

[project.scripts]
backathon = "backathon.cmdline.main:main"

[tool.black]
target-version = ["py39"]
line-length = 90

[tool.ruff]
select = ["E", "F", "W", "B", "TID25", "I"]

ignore = ["E501", "B007", "B024", "B027", "B904", "B905"]
unfixable = ["F841"]


[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
