/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top */
        get: operations["top__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roots */
        get: operations["list_roots_roots__get"];
        put?: never;
        /** Add Root */
        post: operations["add_root_roots__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Root */
        get: operations["get_root_roots__id__get"];
        put?: never;
        post?: never;
        /** Del Root */
        delete: operations["del_root_roots__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/excludes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Excludes */
        get: operations["get_excludes_excludes__get"];
        put?: never;
        /** Set Excludes */
        post: operations["set_excludes_excludes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshots */
        get: operations["get_snapshots_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{objid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_objects__objid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{objid}/ls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Directory Contents
         * @description Given a tree-type object, list the contents of the directory
         */
        get: operations["get_directory_contents_objects__objid__ls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{objid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Object */
        get: operations["download_object_objects__objid__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan */
        get: operations["scan_scan_get"];
        put?: never;
        /** Scan Start */
        post: operations["scan_start_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup */
        get: operations["backup_backup_get"];
        put?: never;
        /** Backup Start */
        post: operations["backup_start_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackupProgress */
        BackupProgress: {
            /**
             * Count Progress
             * @default 0
             */
            count_progress: number;
            /**
             * Count Total
             * @default 0
             */
            count_total: number;
            /**
             * Size Progress
             * @default 0
             */
            size_progress: number;
            /**
             * Size Total
             * @default 0
             */
            size_total: number;
            /**
             * Actual Uploaded
             * @default 0
             */
            actual_uploaded: number;
            /** Current Entries */
            current_entries?: components["schemas"]["_EntryProgress"][];
            /**
             * Objects Processed
             * @default 0
             */
            objects_processed: number;
            /**
             * Objects Uploaded
             * @default 0
             */
            objects_uploaded: number;
        };
        /** Body_add_root_roots__post */
        Body_add_root_roots__post: {
            /** Path */
            path: string;
        };
        /** DirListEntry */
        DirListEntry: {
            /**
             * Id
             * Format: base64
             */
            id: string;
            /** Name */
            name: string;
            obj: components["schemas"]["Object"];
        };
        /**
         * FSEntry
         * @description Represents a row in the fsentry table
         *
         *     Keeps track of an entry in the local filesystem, either a directory,
         *     or a file.
         *
         *     This tracks the last known state of each filesystem entry, so that it can
         *     be compared to the actual state of the filesystem to see if it has changed.
         *
         *     It also keeps track of the last known object ID that was uploaded for
         *     this object. If obj is null, then this entry is considered "dirty"
         *     and needs to be uploaded.
         */
        FSEntry: {
            /** Id */
            id: number;
            /** Objid */
            objid?: string | null;
            /**
             * Path
             * Format: binary
             */
            path: string;
            /** Parent */
            parent?: number | null;
            /**
             * New
             * @default true
             */
            new: boolean;
            /** St Mode */
            st_mode?: number | null;
            /** St Mtime Ns */
            st_mtime_ns?: number | null;
            /** St Size */
            st_size?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Object
         * @description Represents a row in the object table
         *
         *     This table keeps track of what objects exist in the remote repository
         *
         *     The existence of an object in this table implies that an object has been
         *     committed to the repository.
         *
         *     The children relation is used in the calculation of garbage objects. If
         *     an object depends on another in any way, it is added as a "child". Then,
         *     when a root object is deleted, a set of unreachable garbage objects can
         *     be calculated.
         */
        Object: {
            /** Objid */
            objid: string;
            type: components["schemas"]["ObjectType"] | null;
            /** Uploaded Size */
            uploaded_size: number | null;
            /** File Size */
            file_size: number | null;
            /** Last Modified Time */
            last_modified_time: string | null;
            /** Sha1 */
            sha1: string | null;
        };
        /**
         * ObjectType
         * @enum {string}
         */
        ObjectType: "file" | "blob" | "tree" | "symlink";
        /** ScanProgress */
        ScanProgress: {
            /** Scanned */
            scanned: number;
            /** Total */
            total: number | null;
            /** Last Path */
            last_path: string | null;
        };
        /**
         * Snapshot
         * @description A snapshot of a filesystem at a particular time
         */
        Snapshot: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Root */
            root: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** _EntryProgress */
        _EntryProgress: {
            /** Path */
            path: string;
            /**
             * Started
             * @default false
             */
            started: boolean;
            /**
             * Bytes Backed Up
             * @default 0
             */
            bytes_backed_up: number;
            /**
             * Bytes Total
             * @default 0
             */
            bytes_total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    top__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_roots_roots__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FSEntry"][];
                };
            };
        };
    };
    add_root_roots__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_add_root_roots__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FSEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_root_roots__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FSEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    del_root_roots__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_excludes_excludes__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    set_excludes_excludes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshots_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
        };
    };
    get_object_objects__objid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_directory_contents_objects__objid__ls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirListEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_object_objects__objid__download_get: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                objid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanProgress"] | null;
                };
            };
        };
    };
    scan_start_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    backup_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupProgress"] | null;
                };
            };
        };
    };
    backup_start_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
